### ISSUE TITLE
Set APP_KEY in production

### ISSUE THREAD

**Issue by wsanchez** [burningmantech/ranger-clubhouse-api#16]
We currently do not set `APP_KEY` in production.

My understanding is that this is used to encrypt sessions, which implied that the value should be a secret.  In which case, I should run `php artisan key:generate` once and set that value in the staging config, then probably repeat with a new key for production.

@mikeburg that sound right?

**Comment by mikeburg** [comment]
APP_KEY is not being used, since sessions are not being used. 

The Clubhouse uses Json Web Token (JWT) for authentication between the frontend and backend. The token is stateless and  encrypted with JWT_SECRET. The secret should be generated once and only once and used across all container instances. 

Use ```php artisan jwt:secret -s``` to generate a new secret. Copy-and-paste the output to whatever JWT_SECRET is set.

**Comment by wsanchez** [comment]
OK I did that one already, so I think we're set.  Thanks.
