### ISSUE TITLE
Create Docker container to handle worker queues

### ISSUE THREAD

**Issue by mikeburg** [burningmantech/ranger-clubhouse-api#17]
The Clubhouse could benefit from using worker queues to handle long running tasks. One example is using the Ranger Broadcast System to sending an emergency broadcast to all of Rangerdom (aka the Big Red Button). This task can take well over a minute to complete and has caused both the browser and web server to timeout while waiting on the Clubhouse to respond.

The container would need access to the database, the AWS SMTP server, and Twilio's API server. No inbound ports are used. (i.e. no web connection.)

The container should be built in the same way the API server is built -- is there a way to reuse the container?

The command to start monitoring for and executing queue jobs is:

```
$ php artisan queue:work
```
More information can be found at:
https://laravel.com/docs/5.7/queues

**Comment by wsanchez** [comment]
OK.  Should be doable.  I assume this isn't a launch requirement, so scheduling for the event milestone.

**Comment by wsanchez** [comment]
Marking as show stopper on the assumption that this is required for the features in question.

**Comment by mikeburg** [comment]
No, this is not a launch requirement at all. There's nothing using worker queues ATM.

**Comment by wsanchez** [comment]
OK so in AWS, we'll need an additional service which will get updated when the API code changes.

We could also just run it in each API service container, but I don't think running more than one of these is good. There's a chance they step on each other (though I'll assume they wrote it sanely and avoid that), there's no real win to running >1 unless we're throwing lots of concurrent work at the queue, and since it's polling, there's a cost to the containers spinning up occasionally even when nobody is using the service.

Also, as a separate service, we can control the number of queue workers independently of the number of web instances.

**Comment by wsanchez** [comment]
YF says the command to run a queue worker is `php artisan queue:work`.

**Comment by mikeburg** [comment]
The worker queue default is to pole the database every 3 seconds with pessimistic locking - in other words, multiple workers can be running without fear of duplicate job execution.

Other than the occasional RBS spam (shift muster, emergency broadcast, etc) in late August/early September, the worker should be fairly idle. Only a few emails per day will be sent out  during the rest of the year.

Besides handling background emailing, we could consider other ideas.. Like having a background database dump,  syncing Lambase photos, or email a daily report on role changes.

**Comment by wsanchez** [comment]
I think off-playa, or at least in off-peak season, the polling interval it could be a lot less frequent.

**Comment by mikeburg** [comment]
Its a simple SELECT with lock, I doubt it would consume more than 10ms to perform.

**Comment by flwyd** [comment]
> Other than the occasional RBS spam (shift muster, emergency broadcast, etc) in late August/early September, the worker should be fairly idle. Only a few emails per day will be sent out during the rest of the year.

There's also an RBS setting (checked by default?) for "Shift changes."  When I was testing stuff locally, that was generating emails to me when I signed up for a shift, so I think we'll be sending more than a few emails per day during the summer.

There's probably also a rush of Reset Password emails around the time training and/or scheduling goes live.  And it's best if the there's not a long polling delay for those, since someone's actively hitting refresh in their email tab.

> Besides handling background emailing, we could consider other ideas.. Like having a background database dump, syncing Lambase photos, or email a daily report on role changes.

The CH1 implementation of bulk Lambase syncing is "Hit a link and wait around for several minutes," so that sounds like a great thing to move to a worker queue (probably still triggered by a user action, though).

I'm a little skeptical of using a DB-based worker queue for a DB dump.  A mysqldump cronjob sounds like a more robust bet.  (Or we can do something fancier if we're doing on-playa hot backups.)

**Comment by mikeburg** [comment]
>There's also an RBS setting (checked by default?) for "Shift changes." When I was testing stuff locally, that was generating emails to me when I signed up for a shift, so I think we'll be sending more than a few emails per day during the summer.

That's not really the issue here. What's being talked about is the issue of the limit 50 msgs/sec (previous 14 msgs/sec), and a providing a reasonable UI experience. A single one off email, happening every few minutes, is not a concern. I'd really, really be shocked if either Clubhouse could exceed the 50 messages/sec limit from "email one offs" such as shift sign up or password resets.

The original problem is the RBS sending an emergency broadcast and upping the spending limit to avoid creating & maintaining another container to handle worker jobs and to provide a good UI experience. (i.e., "Did the website hang? it's taking soo long.")

Things like Reset Password, and shift sign up notifications  - which are single one off emails and not part of a mass mailing - could be placed in a queue or send immediately.  I could argue it might help performance during a busy sign up period to have most emails placed into a worker queue.  A container  would be freed up to handle more requests since it was not babysitting an email connection.

I really like to do some "science" and verify the assumptions on how costly it would be  for a worker container to poll at various intervals. A Fargate container only costs  $0.04048 per cpu hour. I'd be shocked if a worker container was taking more than 100ms per poll cycle. Assuming that's correct, the price to poll at once per second would be ~$35 per year.

**Comment by wsanchez** [comment]
We shouldn't need a new container image for this, so the work here is a new AWS service config.

**Comment by wsanchez** [comment]
Once this is working, we should revert #99

**Comment by mikeburg** [comment]
In addition to upping the fastcgi_read_timeout value in https://github.com/burningmantech/ranger-clubhouse-api/pull/99 - the AWS load balancer Idle Timeout had to be increased as well. The default is 60 seconds.

When this is implemented, turn down the load balancer idle timeout value back to the default of 60 seconds: EC2 Management > Load Balancers [sidebar] > Rangers  > Attributes  > Idle Timeout.

**Comment by wsanchez** [comment]
Re-opening for follow-through

**Comment by wsanchez** [comment]
Next step is to start a background job in AWS and also have that task bounce when we deploy…

**Comment by mikeburg** [comment]
Worker queues and task scheduling has been implemented by
https://github.com/burningmantech/ranger-clubhouse-api/pull/382

Closing out.
